[build-system]
requires = ["setuptools>=42.0", "wheel", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=slapping"
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]
