[parameters]
epochs = 1
criterion = "VGG16DecoderLossFunction"
batch_size = 5
learning_rate = 0.0005
use_gpu = true

[final_losses]
training = 3059883.5
validation = 3202505.0

[loss_evolution]
training = [ 3059883.5,]
validation = [ 3202505.0,]
